// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, getSettingsSync, updateSettings, updateSettingsWithPasswordEpoch, PasswordEpochMismatchError, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  recordProviderConnectionFallbackState, clearProviderConnectionFallbackState,
  deleteProviderConnection, deleteProviderConnectionsByProvider, setProviderConnectionAutoPing,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, getApiKeyByKey, getApiKeyUsageTotals, getAllApiKeyUsageTotals, incrementApiKeyUsageSync, createApiKey, updateApiKey, deleteApiKey, validateApiKey, getApiKeyUsageLimitStatus,
  upsertProviderQuotaSnapshot, replaceProviderQuotaSnapshotsForSource,
  recordQuotaFetchFailure, getProviderQuotaSnapshot,
  listProviderQuotaSnapshots, getQuotaFetchState, pruneProviderQuotaSnapshots,
  acquireQuotaReservation, markQuotaReservationDispatched,
  heartbeatQuotaReservation, commitQuotaReservation, releaseQuotaReservation,
  reapExpiredQuotaReservations, getQuotaReservationPressure,
  hasActiveDispatchedQuotaReservations, hashQuotaRoute,
  assertNoActiveQuotaReservationsSync,
  QuotaReservationError, QuotaCapacityUnavailableError,
  getCombos, getComboById, getComboByName, getComboForModel,
  createCombo, updateCombo, deleteCombo,
  // MCP gateway
  getInstances, getInstanceById, getInstanceBySlug, getEnabledInstancesByIds,
  createInstance, updateInstance, deleteInstance,
  getGatewayKeys, getGatewayKeyById, createGatewayKey, deleteGatewayKey,
  validateGatewayKey, getGrantsForKey, getGrantsForKeyDetailed, setGrants,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, updateCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  exportDb, importDb,
  saveRequestUsage,
  getTodayConnectionTokenTotals,
} from "@/lib/db/index.js";
